import express from 'express';
import cors from 'cors';
import { XMLParser } from 'fast-xml-parser';
import path from 'path';
import { fileURLToPath } from 'url';
import { registerCompanyIntelligence } from './company-intelligence.js';
import { classifyItem, calculateReputation } from './reputation-engine.js';

const app=express(),PORT=process.env.PORT||3000;
const __filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename);
const parser=new XMLParser({ignoreAttributes:false,attributeNamePrefix:''});
const cache=new Map(),CACHE_TTL=20*60*1000,UA='Aliatek-Enterprise-Intelligence/14.0';
app.use(cors());app.use(express.json({limit:'1mb'}));app.use(express.static(path.join(__dirname,'public')));

const clean=(v='')=>String(v).replace(/<[^>]*>/g,' ').replace(/&[^;]+;/g,' ').replace(/\s+/g,' ').trim();
const asDate=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?null:d};
const host=u=>{try{return new URL(u).hostname.replace(/^www\./,'')}catch{return'unknown'}};
const strip=u=>{try{const x=new URL(u);['utm_source','utm_medium','utm_campaign','utm_term','utm_content','gclid','fbclid'].forEach(k=>x.searchParams.delete(k));return x.toString()}catch{return u}};
async function fetchText(url,options={},timeout=6500){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{...options,signal:c.signal,headers:{'user-agent':UA,accept:'*/*',...(options.headers||{})}});if(!r.ok)throw Error(`${r.status} ${r.statusText}`);return await r.text()}finally{clearTimeout(t)}}
function parseRss(xml,provider){const d=parser.parse(xml),root=d?.rss?.channel||d?.feed||{};let rows=root.item||root.entry||[];if(!Array.isArray(rows))rows=[rows];return rows.map(row=>{const link=typeof row.link==='string'?row.link:row.link?.href||row.guid||'',date=asDate(row.pubDate||row.published||row.updated||row.date);return{title:clean(row.title?.['#text']||row.title),description:clean(row.description||row.summary||row.content||''),url:strip(link),source:clean(row.source?.['#text']||row.source||'')||host(link),provider,published:date?.toISOString()||null,date}}).filter(x=>x.title&&x.url)}
function queries(name){return[...new Set([name,`${name} reviews`,`${name} reputation`,`${name} student experience`,`${name} alumni`,`${name} news`])].slice(0,6)}
async function googleNews(q,days,region='US',lang='en-US',ceid='US:en'){return parseRss(await fetchText(`https://news.google.com/rss/search?q=${encodeURIComponent(`"${q}" when:${days}d`)}&hl=${lang}&gl=${region}&ceid=${ceid}`),`Google News ${region}`)}
async function bingNews(q){return parseRss(await fetchText(`https://www.bing.com/news/search?q=${encodeURIComponent(`"${q}"`)}&format=rss`),'Bing News')}
async function gdelt(q,days){const start=new Date(Date.now()-days*86400000),end=new Date(),fmt=d=>d.toISOString().replace(/[-:TZ.]/g,'').slice(0,14),data=JSON.parse(await fetchText(`https://api.gdeltproject.org/api/v2/doc/doc?query=${encodeURIComponent(`"${q}"`)}&mode=ArtList&maxrecords=120&format=json&startdatetime=${fmt(start)}&enddatetime=${fmt(end)}&sort=HybridRel`,{},8000));return(data.articles||[]).map(a=>{const date=asDate(a.seendate||a.date);return{title:clean(a.title),description:`Coverage detected by GDELT from ${a.domain||'unknown source'}.`,url:strip(a.url),source:a.domain||host(a.url),provider:'GDELT',published:date?.toISOString()||null,date}})}
async function reddit(q,days){const t=days<=7?'week':days<=30?'month':'year',d=JSON.parse(await fetchText(`https://www.reddit.com/search.json?q=${encodeURIComponent(q)}&sort=relevance&t=${t}&limit=75`,{headers:{accept:'application/json'}}));return(d?.data?.children||[]).map(({data:p})=>{const date=asDate((p.created_utc||0)*1000);return{title:clean(p.title),description:clean(p.selftext||`${p.score||0} score · ${p.num_comments||0} comments`),url:`https://www.reddit.com${p.permalink}`,source:`reddit.com/r/${p.subreddit}`,provider:'Reddit',published:date?.toISOString()||null,date}})}
async function newsApi(q,days){if(!process.env.NEWS_API_KEY)return[];const from=new Date(Date.now()-days*86400000).toISOString().slice(0,10),d=JSON.parse(await fetchText(`https://newsapi.org/v2/everything?q=${encodeURIComponent(`"${q}"`)}&from=${from}&language=en&sortBy=relevancy&pageSize=100&apiKey=${process.env.NEWS_API_KEY}`));return(d.articles||[]).map(a=>{const date=asDate(a.publishedAt);return{title:clean(a.title),description:clean(a.description||a.content),url:strip(a.url),source:a.source?.name||host(a.url),provider:'NewsAPI',published:date?.toISOString()||null,date}})}
function authority(source=''){const s=source.toLowerCase();if(/reuters|apnews|bbc|bloomberg|ft.com|wsj|sec.gov|\.edu\b|nature.com|science.org/.test(s))return 96;if(/cnbc|cnn|forbes|time.com|guardian|nytimes|washingtonpost|businesswire|prnewswire/.test(s))return 86;if(/reddit|bsky|youtube/.test(s))return 62;return 74}
function enrich(items,q,days){const seen=new Set(),cutoff=Date.now()-days*86400000,ql=q.toLowerCase();return items.filter(x=>{const k=`${clean(x.title).toLowerCase()}|${strip(x.url)}`;if(!x.title||seen.has(k))return false;seen.add(k);return!x.date||x.date.getTime()>=cutoff}).map(x=>{const text=`${x.title} ${x.description}`,a=authority(x.source),age=x.date?Math.max(0,(Date.now()-x.date.getTime())/86400000):days,recency=Math.max(20,Math.round(100-age*(80/Math.max(days,1)))),relevance=Math.min(100,55+(text.toLowerCase().includes(ql)?35:10)),confidence=Math.round(a*.42+recency*.2+relevance*.38);return classifyItem({...x,authority:a,recency,relevance,confidence})}).sort((a,b)=>b.confidence-a.confidence||(b.date?.getTime()||0)-(a.date?.getTime()||0))}
function analytics(items,providerStatus,company,days){const counts={positive:0,neutral:0,negative:0},source=new Map(),topic=new Map(),day=new Map(),provider=new Map(),sentimentDay=new Map(),stop=new Set(['about','after','again','before','brand','company','could','their','there','these','those','through','today','would','with','from','have','that','this','says','said']);for(const x of items){counts[x.sentiment]++;source.set(x.source,(source.get(x.source)||0)+1);provider.set(x.provider,(provider.get(x.provider)||0)+1);const d=x.published?.slice(0,10)||'Unknown';day.set(d,(day.get(d)||0)+1);if(!sentimentDay.has(d))sentimentDay.set(d,{positive:0,neutral:0,negative:0});sentimentDay.get(d)[x.sentiment]++;clean(`${x.title} ${x.description}`).toLowerCase().split(/[^a-z0-9]+/).filter(w=>w.length>4&&!stop.has(w)).forEach(w=>topic.set(w,(topic.get(w)||0)+1))}
const total=items.length,pct=k=>total?Math.round(counts[k]/total*100):0,avgConfidence=total?Math.round(items.reduce((s,x)=>s+x.confidence,0)/total):0,avgAuthority=total?Math.round(items.reduce((s,x)=>s+x.authority,0)/total):0,rep=calculateReputation(items,company),trust=Math.max(0,Math.min(100,Math.round(avgConfidence*.62+avgAuthority*.28+rep.publicSentiment*.1))),negativePressure=Math.max(0,Math.min(100,Math.round(pct('negative')*.72+Math.min(24,counts.negative*.8)+(100-rep.publicSentiment)*.16))),opportunity=Math.max(0,Math.min(100,Math.round(pct('positive')*.42+rep.reputation*.32+Math.min(total,40)*.25))),top=m=>[...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,12).map(([name,count])=>({name,count})),timeline=[...day.entries()].filter(([d])=>d!=='Unknown').sort((a,b)=>a[0].localeCompare(b[0])).map(([date,count])=>({date,count})),sentimentTimeline=[...sentimentDay.entries()].filter(([d])=>d!=='Unknown').sort((a,b)=>a[0].localeCompare(b[0])).map(([date,v])=>({date,...v})),averageMentionsPerDay=days?Number((total/days).toFixed(1)):0,peak=timeline.reduce((m,x)=>x.count>(m?.count||-1)?x:m,null),summary=total?`${company} has an evidence-weighted reputation of ${rep.reputation}/100. Across ${total} verified mentions, connotation is ${pct('positive')}% positive, ${pct('neutral')}% neutral, and ${pct('negative')}% negative. The score blends long-term brand standing with the weighted tone of current reviews and coverage.`:`No verified public mentions were found for ${company} in the selected ${days}-day window.`,recommendations=[];
if(!total)recommendations.push('Increase indexed public visibility through consistent naming, announcements, and searchable review coverage.');if(negativePressure>=45)recommendations.push('Review the strongest negative, high-authority mentions and address recurring themes.');if(!recommendations.length)recommendations.push('Maintain brand momentum and monitor changes in weighted public connotation.');
return{company,days,generatedAt:new Date().toISOString(),totals:{mentions:total,sources:source.size,providers:providerStatus.filter(x=>x.status==='online').length,...counts},percentages:{positive:pct('positive'),neutral:pct('neutral'),negative:pct('negative')},scores:{reputation:rep.reputation,trust,crisisRisk:negativePressure,negativePressure,opportunity,confidence:avgConfidence,authority:avgAuthority,publicSentiment:rep.publicSentiment,brandPrior:rep.brandPrior,evidenceWeight:rep.evidenceWeight},topTopics:top(topic),topSources:top(source),providerContribution:top(provider),timeline,sentimentTimeline,averageMentionsPerDay,activeDays:timeline.length,peakDay:peak,summary,recommendations,providerStatus}}

app.get('/api/health',(_req,res)=>res.json({status:'ok',version:'14.0.0'}));
registerCompanyIntelligence(app);
app.get('/api/search',async(req,res)=>{const company=clean(req.query.company||req.query.q||''),days=[7,30,90].includes(Number(req.query.days))?Number(req.query.days):30,market=req.query.market==='us'?'us':'global';if(company.length<2)return res.status(400).json({error:'Enter a company, brand, or organization.'});const cacheKey=`v14|${company.toLowerCase()}|${days}|${market}`,cached=cache.get(cacheKey);if(cached&&Date.now()-cached.time<CACHE_TTL)return res.json({...cached.data,cached:true});const qs=queries(company),providers=[],jobs=[],add=(name,fn)=>jobs.push((async()=>{try{const data=await fn();providers.push({name,status:'online',mentions:data.length});return data}catch(e){providers.push({name,status:'limited',mentions:0,message:e.message});return[]}})());
add('Google News US',async()=>(await Promise.all(qs.slice(0,3).map(q=>googleNews(q,days,'US','en-US','US:en')))).flat());
add('Google News Global',async()=>(await Promise.all(qs.slice(0,2).map(q=>googleNews(q,days,'GB','en-GB','GB:en')))).flat());
add('Bing News',async()=>(await Promise.all(qs.slice(0,2).map(bingNews))).flat());
add('GDELT',()=>gdelt(company,days));add('Reddit Reviews',()=>reddit(`${company} review`,days));add('NewsAPI',()=>newsApi(company,days));
const raw=(await Promise.all(jobs)).flat(),items=enrich(raw,company,days).slice(0,1200),payload={version:'14.0.0',query:company,days,market,items,analytics:analytics(items,providers,company,days),cached:false};cache.set(cacheKey,{time:Date.now(),data:payload});res.json(payload)});
app.get('*',(_req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(PORT,()=>console.log(`Aliatek Enterprise v14 running on ${PORT}`));
